sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dockmaker54/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockmaker54/react-test npm test 

after_success:
  - docker build -t dockmaker54/multi-client ./client
  - docker build -t dockmaker54/multi-nginx ./nginx
  - docker build -t dockmaker54/multi-server ./server
  - docker build -t dockmaker54/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dockmaker54/multi-client
  - docker push dockmaker54/multi-nginx
  - docker push dockmaker54/multi-server
  - docker push dockmaker54/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-083020474640
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access-key:
    secure: $AWS_SECRET_KEY

